version: '3.7'
services:
  gocat:
    image: gocat-server:latest
    ports:
      - "8080:8080"
    environment:
        GOCAT_PORT: 8080 
        GOCAT_MODEL_FOLDER: "../models/"
        GOCAT_MAX_CHANNEL: 0
        GOCAT_MAX_MEMORY: 64
