version: '3.7'
services:
  gocat:
    image: gocat-server:latest
    ports:
      - "8080:8080"
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 1.0   
    environment:
        GOCAT_PORT: 8080 
        GOCAT_MODEL_FOLDER: "../models/"
        GOCAT_MAX_CHANNEL: 0
        GOCAT_MAX_MEMORY: 64
        GOCAT_CACHE_COUNT: 100
        GOCAT_CACHE_TTL: 10
